//! 🇺🇸 The enclave against the normative vectors in `apps/sdk/tests/vectors/`, generated by the vault's TypeScript.
//!
//! The Python test-suite runs the same vectors through the Python wrappers;
//! this file runs them through the Rust core directly, so a regression is
//! attributed to the right layer the first time it is seen.
//!
//! 🇧🇷 O enclave contra os vetores normativos em `apps/sdk/tests/vectors/`, gerados pelo TypeScript do cofre.
//!
//! A suíte Python roda os mesmos vetores pelos wrappers Python; este arquivo
//! os roda direto pelo núcleo Rust, para uma regressão ser atribuída à camada
//! certa na primeira vez em que aparece.

use std::path::PathBuf;

use base64::Engine as _;
use serde_json::Value;

use _secure::hybrid::Identity;
use _secure::{aead, kdf, secretstream};

fn vector(name: &str) -> Value {
    let path: PathBuf =
        [env!("CARGO_MANIFEST_DIR"), "..", "tests", "vectors", &format!("{name}.json")].iter().collect();
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    serde_json::from_str(&text).expect("vector is valid JSON")
}

fn b64(value: &Value) -> Vec<u8> {
    let text = value.as_str().expect("b64url string").trim_end_matches('=');
    base64::engine::general_purpose::URL_SAFE_NO_PAD.decode(text).expect("valid base64url")
}

fn text(value: &Value) -> &str {
    value.as_str().expect("string")
}

fn hex(data: &[u8]) -> String {
    use std::fmt::Write as _;
    data.iter().fold(String::new(), |mut out, b| {
        let _ = write!(out, "{b:02x}");
        out
    })
}

#[test]
fn request_signature_hmac_matches() {
    let v = vector("request_signature");
    let key = b64(&v["sign_key_b64url"]);
    let tag = kdf::hmac_sha512(&key, text(&v["canonical_string"]).as_bytes()).unwrap();
    assert_eq!(hex(&tag), text(&v["hmac_sha512_hex"]));
}

#[test]
fn hkdf_with_and_without_salt_matches() {
    let v = vector("aes_gcm_envelope");
    let h = &v["hkdf"];
    let ikm = b64(&h["ikm_b64url"]);
    let info = text(&h["info"]).as_bytes();
    let mut okm = [0u8; 32];
    kdf::hkdf_sha256(&ikm, Some(&b64(&h["salt_b64url"])), info, &mut okm).unwrap();
    assert_eq!(okm.to_vec(), b64(&h["okm_32_b64url"]));
    kdf::hkdf_sha256(&ikm, None, info, &mut okm).unwrap();
    assert_eq!(okm.to_vec(), b64(&h["okm_no_salt_b64url"]));
}

fn open_envelope(wrapping_key: &[u8], payload: &Value, info: &str) -> Vec<u8> {
    let salt = b64(&payload["salt"]);
    let nonce = b64(&payload["nonce"]);
    let ciphertext = b64(&payload["ciphertext"]);
    let mut derived = [0u8; 32];
    kdf::hkdf_sha256(wrapping_key, Some(&salt), info.as_bytes(), &mut derived).unwrap();
    aead::open(&derived, &nonce, &ciphertext, b"").unwrap().to_vec()
}

#[test]
fn wrap_key_and_encrypt_content_payloads_open() {
    let v = vector("aes_gcm_envelope");
    let w = &v["wrap_key"];
    assert_eq!(
        open_envelope(&b64(&w["wrapping_key_b64url"]), &w["payload"], text(&w["info"])),
        b64(&w["plaintext_b64url"])
    );
    let c = &v["encrypt_content"];
    assert_eq!(
        open_envelope(&b64(&c["dek_b64url"]), &c["payload"], text(&c["info"])),
        text(&c["plaintext_utf8"]).as_bytes()
    );
}

#[test]
fn hybrid_seal_opens_with_vector_secrets() {
    let v = vector("hybrid_seal");
    let r = &v["recipient"];
    let identity =
        Identity::from_secrets(&b64(&r["x25519_secret_b64url"]), &b64(&r["mlkem768_secret_b64url"])).unwrap();
    assert_eq!(identity.x25519_public().to_vec(), b64(&r["x25519_public_b64url"]));
    assert_eq!(identity.mlkem768_public().to_vec(), b64(&r["mlkem768_public_b64url"]));
    let s = &v["sealed"];
    let opened =
        identity.open(&b64(&s["salt"]), &b64(&s["nonce"]), &b64(&s["ciphertext"]), text(&v["aad"]).as_bytes()).unwrap();
    assert_eq!(&*opened, text(&v["plaintext_utf8"]).as_bytes());
    assert!(identity.open(&b64(&s["salt"]), &b64(&s["nonce"]), &b64(&s["ciphertext"]), b"wrong").is_err());
}

#[test]
fn secretstream_vector_pulls_every_chunk_and_final_tag() {
    let v = vector("secretstream");
    let key = b64(&v["key_b64url"]);
    let header = b64(&v["header_b64url"]);
    let mut state = [0u8; secretstream::STATE_BYTES];
    secretstream::init(&mut state, &key, &header).unwrap();
    let plaintexts = v["plaintext_chunks_utf8"].as_array().unwrap();
    let ciphers = v["cipher_chunks_b64url"].as_array().unwrap();
    assert_eq!(plaintexts.len(), ciphers.len());
    for (index, (expected, cipher)) in plaintexts.iter().zip(ciphers).enumerate() {
        let (message, tag) = secretstream::pull(&mut state, &b64(cipher), b"").unwrap();
        assert_eq!(message, text(expected).as_bytes());
        let is_last = index + 1 == plaintexts.len();
        assert_eq!(tag == secretstream::TAG_FINAL, is_last, "chunk {index}");
    }

    let framed = b64(&v["framed_body_b64url"]);
    assert_eq!(&framed[..secretstream::HEADER_BYTES], &header[..]);
    let mut offset = secretstream::HEADER_BYTES;
    let mut state = [0u8; secretstream::STATE_BYTES];
    secretstream::init(&mut state, &key, &header).unwrap();
    let mut assembled = Vec::new();
    while offset < framed.len() {
        let len = u32::from_be_bytes(framed[offset..offset + 4].try_into().unwrap()) as usize;
        offset += 4;
        let (message, _tag) = secretstream::pull(&mut state, &framed[offset..offset + len], b"").unwrap();
        assembled.extend(message);
        offset += len;
    }
    let expected: String = plaintexts.iter().map(text).collect();
    assert_eq!(assembled, expected.as_bytes());
}
