"""🇺🇸 Type stubs for `diagnos._secure`, the native memory enclave (Rust, `apps/sdk/native/`).

Only `diagnos.crypto` and `diagnos.session` import this module; application
code never should. Every secret here is a `SecretBox` — bytes that live in
page-locked memory and never come back as `bytes`. The full contract, threat
model and the reasons behind each method are in `apps/sdk/native/README.md`.

🇧🇷 Stubs de tipo de `diagnos._secure`, o enclave de memória nativo (Rust, `apps/sdk/native/`).

Só `diagnos.crypto` e `diagnos.session` importam este módulo; código de
aplicação nunca deveria. Todo segredo aqui é um `SecretBox` — bytes que
vivem em memória travada em página e nunca voltam como `bytes`. O contrato
completo, o modelo de ameaça e o porquê de cada método estão em
`apps/sdk/native/README.md`.
"""

from __future__ import annotations

from typing import Any, Final

_Buffer = bytes | bytearray | memoryview

__version__: Final[str]
SECRETSTREAM_HEADER_BYTES: Final[int]
SECRETSTREAM_ABYTES: Final[int]
X25519_PUBLIC_BYTES: Final[int]
X25519_SECRET_BYTES: Final[int]
MLKEM768_PUBLIC_BYTES: Final[int]
MLKEM768_SECRET_BYTES: Final[int]
MLKEM768_CIPHERTEXT_BYTES: Final[int]

class SecureError(Exception):
    """🇺🇸 Any failure inside the enclave. 🇧🇷 Qualquer falha dentro do enclave."""

class SecretBox:
    """🇺🇸 Bytes in locked memory; no `bytes()` way out except `reveal()`.

    🇧🇷 Bytes em memória travada; sem saída para `bytes()` além de `reveal()`.
    """

    @staticmethod
    def random(length: int) -> SecretBox: ...
    @staticmethod
    def from_bytes(data: _Buffer) -> SecretBox: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    @property
    def is_locked(self) -> bool: ...
    @property
    def is_wiped(self) -> bool: ...
    def wipe(self) -> None: ...
    def clone(self) -> SecretBox: ...
    def reveal(self) -> bytearray: ...
    def hmac_sha512(self, message: _Buffer) -> bytes: ...
    def hkdf_sha256(self, *, info: _Buffer, length: int = 32, salt: _Buffer | None = None) -> SecretBox: ...
    def aes_gcm_seal(self, nonce: _Buffer, plaintext: _Buffer, aad: _Buffer | None = None) -> bytes: ...
    def aes_gcm_seal_secret(self, nonce: _Buffer, secret: SecretBox, aad: _Buffer | None = None) -> bytes: ...
    def aes_gcm_open(self, nonce: _Buffer, ciphertext: _Buffer, aad: _Buffer | None = None) -> bytes: ...
    def aes_gcm_open_secret(self, nonce: _Buffer, ciphertext: _Buffer, aad: _Buffer | None = None) -> SecretBox: ...
    def aes_gcm_open_json_field(
        self, nonce: _Buffer, ciphertext: _Buffer, aad: _Buffer | None, field: str
    ) -> SecretBox: ...

class HybridKeyPair:
    """🇺🇸 X25519 + ML-KEM-768 identity, private halves locked.

    🇧🇷 Identidade X25519 + ML-KEM-768, metades privadas travadas.
    """

    @staticmethod
    def generate() -> HybridKeyPair: ...
    @staticmethod
    def from_secrets(x25519_secret: SecretBox, mlkem768_secret: SecretBox) -> HybridKeyPair: ...
    @property
    def x25519_public(self) -> bytes: ...
    @property
    def mlkem768_public(self) -> bytes: ...
    @property
    def is_wiped(self) -> bool: ...
    def x25519_secret(self) -> SecretBox: ...
    def mlkem768_secret(self) -> SecretBox: ...
    def open(self, encapsulation: _Buffer, nonce: _Buffer, ciphertext: _Buffer, aad: _Buffer) -> bytes: ...
    def open_secret(self, encapsulation: _Buffer, nonce: _Buffer, ciphertext: _Buffer, aad: _Buffer) -> SecretBox: ...
    def open_session(
        self, encapsulation: _Buffer, nonce: _Buffer, ciphertext: _Buffer, aad: _Buffer
    ) -> tuple[str, int, SecretBox, SecretBox]: ...
    def wipe(self) -> None: ...

class SecretStreamPush:
    """🇺🇸 libsodium secretstream, encrypting side. 🇧🇷 secretstream do libsodium, lado que cifra."""

    def __init__(self, key: SecretBox) -> None: ...
    @property
    def header(self) -> bytes: ...
    @property
    def is_finished(self) -> bool: ...
    def push(self, message: _Buffer, *, final: bool = False, ad: _Buffer | None = None) -> bytes: ...

class SecretStreamPull:
    """🇺🇸 libsodium secretstream, decrypting side. 🇧🇷 secretstream do libsodium, lado que decifra."""

    def __init__(self, key: SecretBox, header: _Buffer) -> None: ...
    @property
    def is_finished(self) -> bool: ...
    def pull(self, chunk: _Buffer, *, ad: _Buffer | None = None) -> tuple[bytes, bool]: ...

class EntropyPool:
    """🇺🇸 OS randomness mixed with the vault's session seed.

    🇧🇷 Aleatoriedade do SO misturada com a semente de sessão do cofre.
    """

    def __init__(self) -> None: ...
    def mix(self, seed: SecretBox | _Buffer) -> None: ...
    def random(self, n: int) -> bytes: ...
    def random_secret(self, n: int) -> SecretBox: ...

def seal_hybrid(
    x25519_public: _Buffer, mlkem768_public: _Buffer, plaintext: _Buffer, aad: _Buffer
) -> tuple[bytes, bytes, bytes]: ...
def harden_process() -> dict[str, Any]: ...
def memory_status() -> dict[str, Any]: ...
